spring.application.name=security

# database details
spring.datasource.url=jdbc:postgresql://localhost:5432/security_database
spring.datasource.username=user1
spring.datasource.password=user060625

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql= true
spring.jpa.database = postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#jwt_secret =/EH4pOWzUfvHzUQgH0EQD/RGjusg3ycJwOH+f12mvECTkuWzrLNrA408gLFoRyO3lJ1XqgLiuXziQail9k1Bbr5S5jrqQL0vqCNrAmOEX+d0rZtNFqUXtbpo4RqwPYg0KDM0Sats/eomaoEVl6Am1mcL0fk/udf28Y+G8X50E+yu/bd7szcVOoXwvhv163Ho0zIdamNm1t2L9Wf/x9lgiE8gU1k/YtKWxXYh8xbAM8Mit/5ZCxCFKoVY5z/dyNgffQpUwn58I+p7u8etNQoZEP+RbCmNfUOEc0dbGK3TWNlg75GqC05kMWQ08qihjcqF7e2ZsW+j0Rw+Un6ihwY5uPtrQO71B8VqHTDZ+MrMFLI=

